user_overwrite:
    resource: "@UserOverwriteBundle/Controller/"
    type:     annotation
    prefix:   /api/

web:
    resource: '@WebBundle/Controller/'
    type: annotation

api:
    resource: '@ApiBundle/Controller/api'
    type: rest
    prefix: /api/

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
