web:
    resource: '@WebBundle/Controller/'
    type: annotation

api:
    resource: '@ApiBundle/Controller/'
    type: rest
    prefix: /api

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
