<?php

namespace ApiBundle\Repository;

/**
 * FoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodRepository extends \Doctrine\ORM\EntityRepository
{
  /**
  * @return string
  **/
  public function getFood($food_id)
  {
    $query = "SELECT * FROM food f WHERE id = :id";
    $params = array(
      "id" => $food_id
    );
    $array = $this->getEntityManager()->getConnection()->executeQuery($query, $params)->fetchAll();
    return $array[0]["name"];
  }
}
