<?php

namespace ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  /**
  * @return string
  **/
  public function filter($age = "", $gender = "")
  {
    return "salut jai " . $age . "ans et je suis un/une " . $gender;
  }
}
